[package]
name = "vault-init-tx"
version = "0.1.0"

[lib]
kind = "tx-script"
namespace = "miden:vault-init-tx"

[dependencies]
vault-account = { path = "../vault-account" }

[package.metadata.miden.dependencies]
vault-account = { wit = "../vault-account/target/generated-wit" }
